# Generated by Django 4.0.4 on 2022-04-23 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Приятелски', 'Приятелски'), ('спортен', 'спортен'), ('културен', 'културен'), ('граждански', 'граждански'), ('комерсиален', 'комерсиален'), ('политически', 'политически')], max_length=11)),
                ('description', models.TextField(max_length=255)),
                ('location', models.CharField(max_length=50)),
                ('likes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('is_displayed', models.BooleanField(default=True)),
                ('invited_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_users', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('organizer', 'title')},
            },
        ),
    ]
