# Generated by Django 4.0.4 on 2022-04-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_publication_date_remove_event_invited_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recommendations',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
